In [1]:
import pandas as pd

In [2]:
base = pd.read_csv('data/house_prices.csv')

In [4]:
base.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [15]:
import numpy as np

In [48]:
x = np.zeros((len(base), 4))
y = np.zeros(len(base))

In [49]:
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 ...
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [50]:
for i in range(len(base)):
    x[i] = [base.iloc[i][3], base.iloc[i][4], base.iloc[i][5], base.iloc[i][6]]
    y[i] = base.iloc[i][2]

In [51]:
print(x)
print(y)

[[3.000e+00 1.000e+00 1.180e+03 5.650e+03]
 [3.000e+00 2.250e+00 2.570e+03 7.242e+03]
 [2.000e+00 1.000e+00 7.700e+02 1.000e+04]
 ...
 [2.000e+00 7.500e-01 1.020e+03 1.350e+03]
 [3.000e+00 2.500e+00 1.600e+03 2.388e+03]
 [2.000e+00 7.500e-01 1.020e+03 1.076e+03]]
[221900. 538000. 180000. ... 402101. 400000. 325000.]


In [56]:
x_train = x[:int(len(x)*0.7)]
x_test = x[int(len(x)*0.7):]
y_train = y[:int(len(y)*0.7)]
y_test = y[int(len(y)*0.7):]
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(15129, 4)
(6484, 4)
(15129,)
(6484,)


In [57]:
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score

In [58]:
regr = linear_model.LinearRegression()

In [59]:
regr.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [61]:
y_pred = regr.predict(x_test)

In [62]:
mean_squared_error(y_test, y_pred)

66767397242.02784

In [64]:
regr.coef_

array([-6.07513000e+04,  1.40957758e+03,  3.21316795e+02, -3.72077570e-01])

In [67]:
for i in range(10):
    print(round(y_pred[i], 1), y_test[i])

669290.3 937750.0
864876.7 725126.0
168692.0 135000.0
792613.9 635000.0
211703.1 245500.0
392386.8 230000.0
725580.4 1770000.0
478054.4 425000.0
297371.0 220000.0
495575.0 370000.0
